### ISSUE TITLE
error 500 with NoMethodError undefined method `to_time'

### ISSUE THREAD

**Issue by zhongw** [momibun926/redmine_issue_evm#100]
I installed EVM plugin with master branch, when a enable EVM and got the following error, the familiar issues: #84 #88  
```Started GET "/projects/itc/evms" for 10.103.0.12 at 2019-01-03 16:04:13 +0800
Processing by EvmsController#index as HTML
  Parameters: {"project_id"=>"itc"}
  Current user: zhongwei (id=5)
Completed 500 Internal Server Error in 324ms (ActiveRecord: 8.8ms)

NoMethodError (undefined method `to_time' for nil:NilClass):

plugins/redmine_issue_evm/lib/evm_logic.rb:387:in `block in calculate_earned_value'
plugins/redmine_issue_evm/lib/evm_logic.rb:373:in `calculate_earned_value'
plugins/redmine_issue_evm/lib/evm_logic.rb:43:in `initialize'
plugins/redmine_issue_evm/app/controllers/evms_controller.rb:47:in `new'
plugins/redmine_issue_evm/app/controllers/evms_controller.rb:47:in `index'
lib/redmine/sudo_mode.rb:63:in `sudo_mode'
plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:68:in `call'
```

**Comment by momibun926** [comment]
Is there the ticket which a progress rate was set?
In a history of issue, is it shown a progress rate was set?

**Comment by zhongw** [comment]
take your time please.
the instance has many tickets which the progress rate were set, the status and the progress rate is not consistent for some tickets.

**Comment by momibun926** [comment]
hi @zhongw 
I just pushed master repo.
Try it.
