### ISSUE TITLE
NameError (uninitialized constant EvmsController::Evmsetting):

### ISSUE THREAD

**Issue by momibun926** [momibun926/redmine_issue_evm#108]
Branch:redmine3-4-3

EVMの設定ページのモデルクラスが読み込めない

**Comment by momibun926** [comment]
NameError (uninitialized constant EvmsController::Evmsetting):
  plugins/redmine_issue_evm/app/controllers/evms_controller.rb:17:in `index'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by momibun926** [comment]
モデルのクラスファイル名を間違えていた。
emvbsetting.rb -> emvsetting.rb
