### ISSUE TITLE
The symbol for the table 'evmbaselines' is different in migration files

### ISSUE THREAD

**Issue by urimaro** [momibun926/redmine_issue_evm#48]
When I executed `reke redmine:plugins:migrate`, I got an error as below.

```
$ RAILS_ENV=production bundle exec rake redmine:plugins:migrate
Your Gemfile lists the gem mime-types (>= 0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of just one of them later.
Migrating redmine_issue_evm (Redmine Issue Evm plugin)...
== 3 AddColumnEvmbaselines: migrating =========================================
-- add_column(:Evmbaselines, :author_id, :integer)
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Table 'redmine_310_seed.Evmbaselines' doesn't exist: ALTER TABLE `Evmbaselines` ADD `author_id` int(11)/var/rails/redmine-3.1.0-seed/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:305:in `query'
/var/rails/redmine-3.1.0-seed/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:305:in `block in execute'
/var/rails/redmine-3.1.0-seed/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract_adapter.rb:473:in `block in log'
/var/rails/redmine-3.1.0-seed/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.3/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/var/rails/redmine-3.1.0-seed/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract_adapter.rb:467:in `log'
/var/rails/redmine-3.1.0-seed/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:305:in `execute'
/var/rails/redmine-3.1.0-seed/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/mysql2_adapter.rb:231:in `execute'
/var/rails/redmine-3.1.0-seed/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/schema_statements.rb:393:in `add_column'
/var/rails/redmine-3.1.0-seed/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.3/lib/active_record/migration.rb:661:in `block in method_missing'
/var/rails/redmine-3.1.0-seed/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.3/lib/active_record/migration.rb:631:in `block in say_with_time'
/var/rails/redmine-3.1.0-seed/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.3/lib/active_record/migration.rb:631:in `say_with_time'
/var/rails/redmine-3.1.0-seed/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.3/lib/active_record/migration.rb:651:in `method_missing'
/var/rails/redmine-3.1.0-seed/plugins/redmine_issue_evm/db/migrate/003_add_column_evmbaselines.rb:3:in `change'
/var/rails/redmine-3.1.0-seed/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.3/lib/active_record/migration.rb:605:in `exec_migration'
/var/rails/redmine-3.1.0-seed/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.3/lib/active_record/migration.rb:589:in `block (2 levels) in migrate'
/var/rails/redmine-3.1.0-seed/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.3/lib/active_record/migration.rb:588:in `block in migrate'
/var/rails/redmine-3.1.0-seed/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/var/rails/redmine-3.1.0-seed/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.3/lib/active_record/migration.rb:587:in `migrate'
/var/rails/redmine-3.1.0-seed/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.3/lib/active_record/migration.rb:764:in `migrate'
/var/rails/redmine-3.1.0-seed/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.3/lib/active_record/migration.rb:994:in `block in execute_migration_in_transaction'
/var/rails/redmine-3.1.0-seed/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.3/lib/active_record/migration.rb:1042:in `ddl_transaction'
/var/rails/redmine-3.1.0-seed/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.3/lib/active_record/migration.rb:993:in `execute_migration_in_transaction'
/var/rails/redmine-3.1.0-seed/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.3/lib/active_record/migration.rb:955:in `block in migrate'
/var/rails/redmine-3.1.0-seed/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.3/lib/active_record/migration.rb:951:in `each'
/var/rails/redmine-3.1.0-seed/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.3/lib/active_record/migration.rb:951:in `migrate'
/var/rails/redmine-3.1.0-seed/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.3/lib/active_record/migration.rb:819:in `up'
/var/rails/redmine-3.1.0-seed/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.3/lib/active_record/migration.rb:797:in `migrate'
/var/rails/redmine-3.1.0-seed/lib/redmine/plugin.rb:481:in `migrate_plugin'
/var/rails/redmine-3.1.0-seed/lib/redmine/plugin.rb:453:in `migrate'
/var/rails/redmine-3.1.0-seed/lib/redmine/plugin.rb:467:in `block in migrate'
/var/rails/redmine-3.1.0-seed/lib/redmine/plugin.rb:466:in `each'
/var/rails/redmine-3.1.0-seed/lib/redmine/plugin.rb:466:in `migrate'
/var/rails/redmine-3.1.0-seed/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
```

I found a difference of the table name between `db/migrate/001_create_evmbaselines.rb` and `db/migrate/003_add_column_evmbaselines.rb`.
In `001_create_evmbaselines.rb`, the symbol `:evmbaselines` is used.
But in `003_add_column_evmbaselines.rb`, the symbol is `:Evmbaselines`.

In the case of the MySQL, if the variable `lower_case_table_names` which is the MySQL's variable is "0", this error is caused by using different symbol for the table name.

**Comment by momibun926** [comment]
@urimaro Thank you for report.
I changed the table name to the small letter.
Just now pushed to master.
