### ISSUE TITLE
when I opened the evm page with  500 error

### ISSUE THREAD

**Issue by archonwang** [momibun926/redmine_issue_evm#80]
@momibun926 ,
when I opened the evm page with  500 error, please help to check it. Thanks so much.

I have installed the redmine_issue_evm newest version..
and my environment is Redmine3.3.2 with ruby 2.2.4

Error Log
```
Started GET "/projects/sesametranslate?jump=issuevm" for 192.168.60.238 at 2017-04-10 11:57:51 +0800
Processing by ProjectsController#show as HTML
  Parameters: {"jump"=>"issuevm", "id"=>"sesametranslate"}
  Current user: hui.wang (id=8)
Redirected to http://192.168.1.41/projects/sesametranslate/evms
Completed 302 Found in 12ms (ActiveRecord: 3.2ms)
Started GET "/projects/sesametranslate/evms" for 192.168.60.238 at 2017-04-10 11:57:51 +0800
Processing by EvmsController#index as HTML
  Parameters: {"project_id"=>"sesametranslate"}
  Current user: hui.wang (id=8)
Completed 500 Internal Server Error in 283ms (ActiveRecord: 21.4ms)

ArgumentError (comparison of Date with nil failed):
  plugins/redmine_issue_evm/lib/evm_logic.rb:409:in `<='
  plugins/redmine_issue_evm/lib/evm_logic.rb:409:in `sort_and_sum_evm_hash'
  plugins/redmine_issue_evm/lib/evm_logic.rb:389:in `calculate_actual_cost'
  plugins/redmine_issue_evm/lib/evm_logic.rb:37:in `initialize'
  plugins/redmine_issue_evm/app/controllers/evms_controller.rb:58:in `new'
  plugins/redmine_issue_evm/app/controllers/evms_controller.rb:58:in `block in index'
  plugins/redmine_issue_evm/app/controllers/evms_controller.rb:53:in `each'
  plugins/redmine_issue_evm/app/controllers/evms_controller.rb:53:in `index'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'


Started GET "/projects/sesametranslate/evms" for 192.168.60.238 at 2017-04-10 11:57:52 +0800
Processing by EvmsController#index as */*
  Parameters: {"project_id"=>"sesametranslate"}
  Current user: hui.wang (id=8)
Completed 500 Internal Server Error in 287ms (ActiveRecord: 22.1ms)

ArgumentError (comparison of Date with nil failed):
  plugins/redmine_issue_evm/lib/evm_logic.rb:409:in `<='
  plugins/redmine_issue_evm/lib/evm_logic.rb:409:in `sort_and_sum_evm_hash'
  plugins/redmine_issue_evm/lib/evm_logic.rb:389:in `calculate_actual_cost'
  plugins/redmine_issue_evm/lib/evm_logic.rb:37:in `initialize'
  plugins/redmine_issue_evm/app/controllers/evms_controller.rb:58:in `new'
  plugins/redmine_issue_evm/app/controllers/evms_controller.rb:58:in `block in index'
  plugins/redmine_issue_evm/app/controllers/evms_controller.rb:53:in `each'
  plugins/redmine_issue_evm/app/controllers/evms_controller.rb:53:in `index'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by archonwang** [comment]
@momibun926 , sorry to disturb you.
I checked out again for 3.7.2 and there's no error again. Thanks.
