### ISSUE TITLE
open settings page occur  500 error

### ISSUE THREAD

**Issue by archonwang** [momibun926/redmine_issue_evm#86]
@momibun926 , please check it. Thanks.

my environment is remdine 3.3 with holidays gem 3.2.0

```
Started GET "/settings/plugin/redmine_issue_evm" for 192.168.20.231 at 2017-05-05 10:03:10 +0800
Processing by SettingsController#plugin as */*
  Parameters: {"id"=>"redmine_issue_evm"}
  Current user: hui.wang (id=8)
  Rendered plugins/redmine_issue_evm/app/views/settings/_issue_evm_settings.html.erb (207.4ms)
  Rendered settings/plugin.html.erb within layouts/admin (209.2ms)
Completed 500 Internal Server Error in 221ms (ActiveRecord: 2.4ms)

ActionView::Template::Error (undefined method `available_regions' for Holidays:Module):
    16: </p>
    17: <p>
    18:   <%=l(:label_region)%>
    19:   <%= select_tag('settings[region]', options_for_select(Holidays.available_regions, @settings[:region])) %>
    20: </p>
  plugins/redmine_issue_evm/app/views/settings/_issue_evm_settings.html.erb:19:in `_bb829a2a1e9e544fd62ae58fefc4e1a1'
  plugins/redmine_workflow_enhancements/lib/workflow_enhancements/patches/action_view_rendering.rb:53:in `render_with_workflow_enhancements'
  app/views/settings/plugin.html.erb:6:in `block in _97bae4fe216bf907e022e012d491fb68'
  app/views/settings/plugin.html.erb:4:in `_97bae4fe216bf907e022e012d491fb68'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by momibun926** [comment]
i think same as #87

**Comment by momibun926** [comment]
latest version of holiday gem is 5.6.

**Comment by archonwang** [comment]
o it's OK now. Thanks. by the way, could you give me the
