### ISSUE TITLE
open evms occur 500 error

### ISSUE THREAD

**Issue by archonwang** [momibun926/redmine_issue_evm#87]
@momibun926 , please help to check it. Thanks.
when I open the evm page, it occured. 

```

Started GET "/projects/uth_testteam/evms" for 192.168.20.231 at 2017-05-05 10:09:13 +0800
Processing by EvmsController#index as HTML
  Parameters: {"project_id"=>"uth_testteam"}
  Current user: hui.wang (id=8)
Completed 500 Internal Server Error in 47ms (ActiveRecord: 10.3ms)

NoMethodError (undefined method `to_sym' for nil:NilClass):
  plugins/redmine_issue_evm/lib/evm_logic.rb:447:in `block in working_days'
  plugins/redmine_issue_evm/lib/evm_logic.rb:447:in `reject'
  plugins/redmine_issue_evm/lib/evm_logic.rb:447:in `working_days'
  plugins/redmine_issue_evm/lib/evm_logic.rb:347:in `block in calculate_planed_value'
  plugins/redmine_issue_evm/lib/evm_logic.rb:345:in `calculate_planed_value'
  plugins/redmine_issue_evm/lib/evm_logic.rb:34:in `initialize'
  plugins/redmine_issue_evm/app/controllers/evms_controller.rb:41:in `new'
  plugins/redmine_issue_evm/app/controllers/evms_controller.rb:41:in `index'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'


Started GET "/projects/uth_testteam/evms" for 192.168.20.231 at 2017-05-05 10:09:13 +0800
Processing by EvmsController#index as */*
  Parameters: {"project_id"=>"uth_testteam"}
  Current user: hui.wang (id=8)
Completed 500 Internal Server Error in 42ms (ActiveRecord: 7.1ms)

NoMethodError (undefined method `to_sym' for nil:NilClass):
  plugins/redmine_issue_evm/lib/evm_logic.rb:447:in `block in working_days'
  plugins/redmine_issue_evm/lib/evm_logic.rb:447:in `reject'
  plugins/redmine_issue_evm/lib/evm_logic.rb:447:in `working_days'
  plugins/redmine_issue_evm/lib/evm_logic.rb:347:in `block in calculate_planed_value'
  plugins/redmine_issue_evm/lib/evm_logic.rb:345:in `calculate_planed_value'
  plugins/redmine_issue_evm/lib/evm_logic.rb:34:in `initialize'
  plugins/redmine_issue_evm/app/controllers/evms_controller.rb:41:in `new'
  plugins/redmine_issue_evm/app/controllers/evms_controller.rb:41:in `index'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

```

**Comment by momibun926** [comment]
Thakyou for report.
Please try to "bundle install".

**Comment by momibun926** [comment]
I fixed some bugs. Please get the latest code and try.
[https://github.com/momibun926/redmine_issue_evm/releases/tag/3.9.1](url)
or
Pull latest master brunch.

**Comment by momibun926** [comment]
@archonwang 
Did you confirm that it works correctly?

**Comment by archonwang** [comment]
@momibun926 , 
I checked it this morning and it worked correctly. 

 Thanks so much.
