### ISSUE TITLE
open EVM tab page occured 500 error

### ISSUE THREAD

**Issue by archonwang** [momibun926/redmine_issue_evm#88]
Hi, @momibun926 , please check it. Thanks
I am not sure why it happened, for in some projects it worked well.

error log

```
Started GET "/projects/zmss/evms" for 192.168.20.231 at 2017-05-18 12:40:33 +0800
Processing by EvmsController#index as HTML
  Parameters: {"project_id"=>"zmss"}
  Current user: hui.wang (id=8)
Completed 500 Internal Server Error in 7641ms (ActiveRecord: 173.0ms)

ArgumentError (bad value for range):
  plugins/redmine_issue_evm/lib/evm_logic.rb:447:in `working_days'
  plugins/redmine_issue_evm/lib/evm_logic.rb:348:in `block in calculate_planed_value'
  plugins/redmine_issue_evm/lib/evm_logic.rb:346:in `calculate_planed_value'
  plugins/redmine_issue_evm/lib/evm_logic.rb:35:in `initialize'
  plugins/redmine_issue_evm/app/controllers/evms_controller.rb:60:in `new'
  plugins/redmine_issue_evm/app/controllers/evms_controller.rb:60:in `block in index'
  plugins/redmine_issue_evm/app/controllers/evms_controller.rb:55:in `each'
  plugins/redmine_issue_evm/app/controllers/evms_controller.rb:55:in `index'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

```

**Comment by momibun926** [comment]
@archonwang 
Thank you for report.
ISSUE with no start date is used to calculate EVM. This is a bug, so fix it.

**Comment by momibun926** [comment]
I pushed to the latest master. try it.

**Comment by archonwang** [comment]
@momibun926 , 
Checked and it worked well. 
Thanks.
